/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author felip
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form TaskDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBar = new javax.swing.JPanel();
        jLabelToolBarTitle = new javax.swing.JLabel();
        jLabelToolBarAdd = new javax.swing.JLabel();
        jPanelTaskInput = new javax.swing.JPanel();
        jLabelTaskInputName = new javax.swing.JLabel();
        jTextFieldTaskInputName = new javax.swing.JTextField();
        jLabelTaskInputDescription = new javax.swing.JLabel();
        jScrollPaneTaskInputDescription = new javax.swing.JScrollPane();
        jTextAreaTaskInputDescription = new javax.swing.JTextArea();
        jLabelTaskInputDeadline = new javax.swing.JLabel();
        jTextFieldTaskInputDeadline = new javax.swing.JTextField();
        jLabelTaskInputNote = new javax.swing.JLabel();
        jScrollPaneTaskInputNote = new javax.swing.JScrollPane();
        jTextAreaTaskInputNote = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(415, 600));
        setPreferredSize(new java.awt.Dimension(415, 600));

        jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));
        jPanelToolBar.setMinimumSize(new java.awt.Dimension(400, 80));

        jLabelToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToolBarTitle.setText("Tarefas");

        jLabelToolBarAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check/check (4).png"))); // NOI18N

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(jLabelToolBarAdd)
                .addContainerGap())
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelToolBarTitle)
                    .addComponent(jLabelToolBarAdd))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabelTaskInputName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelTaskInputName.setText("Nome");

        jTextFieldTaskInputName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabelTaskInputDescription.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelTaskInputDescription.setText("Descrição");

        jTextAreaTaskInputDescription.setColumns(20);
        jTextAreaTaskInputDescription.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextAreaTaskInputDescription.setRows(5);
        jScrollPaneTaskInputDescription.setViewportView(jTextAreaTaskInputDescription);

        jLabelTaskInputDeadline.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelTaskInputDeadline.setText("Prazo");

        jTextFieldTaskInputDeadline.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabelTaskInputNote.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelTaskInputNote.setText("Notas");

        jTextAreaTaskInputNote.setColumns(20);
        jTextAreaTaskInputNote.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextAreaTaskInputNote.setRows(5);
        jScrollPaneTaskInputNote.setViewportView(jTextAreaTaskInputNote);

        javax.swing.GroupLayout jPanelTaskInputLayout = new javax.swing.GroupLayout(jPanelTaskInput);
        jPanelTaskInput.setLayout(jPanelTaskInputLayout);
        jPanelTaskInputLayout.setHorizontalGroup(
            jPanelTaskInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTaskInputName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldTaskInputName)
            .addComponent(jScrollPaneTaskInputDescription)
            .addComponent(jTextFieldTaskInputDeadline)
            .addGroup(jPanelTaskInputLayout.createSequentialGroup()
                .addGroup(jPanelTaskInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTaskInputDescription)
                    .addComponent(jLabelTaskInputDeadline)
                    .addComponent(jLabelTaskInputNote))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPaneTaskInputNote)
        );
        jPanelTaskInputLayout.setVerticalGroup(
            jPanelTaskInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaskInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTaskInputName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTaskInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTaskInputDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTaskInputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTaskInputDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTaskInputDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTaskInputNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTaskInputNote, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTaskInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTaskInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTaskInputDeadline;
    private javax.swing.JLabel jLabelTaskInputDescription;
    private javax.swing.JLabel jLabelTaskInputName;
    private javax.swing.JLabel jLabelTaskInputNote;
    private javax.swing.JLabel jLabelToolBarAdd;
    private javax.swing.JLabel jLabelToolBarTitle;
    private javax.swing.JPanel jPanelTaskInput;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPaneTaskInputDescription;
    private javax.swing.JScrollPane jScrollPaneTaskInputNote;
    private javax.swing.JTextArea jTextAreaTaskInputDescription;
    private javax.swing.JTextArea jTextAreaTaskInputNote;
    private javax.swing.JTextField jTextFieldTaskInputDeadline;
    private javax.swing.JTextField jTextFieldTaskInputName;
    // End of variables declaration//GEN-END:variables
}
